# Generated by Django 4.1.3 on 2022-11-21 18:46

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('overview', models.TextField(verbose_name='Описание')),
                ('big_image', models.ImageField(default='static/img/listing/details/listing-hero.jpg', upload_to='big/', verbose_name='Большая картинка')),
                ('med_image', models.ImageField(default='static/img/listing/list-3.jpg', upload_to='med', verbose_name='Средняя картинка')),
                ('small_image', models.ImageField(default='static/img/listing/list_icon-3.png', upload_to='small', verbose_name='Маленькая картинка')),
                ('adress', models.CharField(max_length=40, verbose_name='Адресс')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('coord', models.CharField(max_length=40, verbose_name='Координаты')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('min_check', models.IntegerField(default=0, verbose_name='Минимальный чек')),
                ('max_check', models.IntegerField(default=100, verbose_name='Максимальный чек')),
                ('state', models.BooleanField(default=False, verbose_name='Открыто')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
            ],
            options={
                'verbose_name': 'Листинг',
                'verbose_name_plural': 'Листинги',
                'db_table': 'listings',
                'ordering': ('date_published', 'rating', 'state', 'min_check', 'max_check'),
            },
        ),
    ]
